### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by CMecrow** [CMecrow/love-running#1]
As an admin, I can publish a poll to collect users feedback 

**Acceptance Criteria**
- Admin page
- Template tool to create a poll, select question type / number of questions
- Choice of where to publish the poll

**Tasks**
- [ ] Design an admin page
- [ ] HTML / CSS for admin page
- [ ] Create template for polls
- [ ] Code template options
